"""Insert audited same-chain outcomes in manuscript, SI and reviewer response."""
import json,re
import pandas as pd
from common import ROOT,OUT,dump

def main():
    p=OUT/'timeseries';paper=ROOT/'paper';audit=json.loads((p/'audit.json').read_text());assert audit['all_twelve_stages_complete']
    s=json.loads((p/'matched_summary.json').read_text());bins=pd.read_csv(p/'support_quality_bins.csv');held=pd.read_csv(p/'heldout_support_bins.csv');conf=pd.read_csv(p/'support_finalmask_confusion.csv')
    low=bins[(bins.support=='matched437')&bins.bin_lower.eq(0)].iloc[0];high=bins[(bins.support=='matched437')&bins.bin_lower.eq(.8)].iloc[0]
    c=conf[(conf.support=='legacy28')&conf.threshold.eq(.5)];lowpass=c[~c.predicted_supported&c.final_valid].iloc[0];highfail=c[c.predicted_supported&~c.final_valid].iloc[0]
    def used(branch):
        t=(p/('TS_'+branch)/'info/13parameters.txt').read_text();return int(re.search(r'^n_ifg:\s+(\d+)',t,re.M).group(1))
    v={'FULLUSED':str(used('full')),'TRAINUSED':str(used('train')),'VALIDPIX':f"{100*s['final_valid_pixel_fraction']:.2f}",'VALIDPOP':f"{100*s['final_valid_population_fraction']:.2f}",'LOWVALID':f'{100*low.final_valid_pixel_fraction:.2f}','HIGHVALID':f'{100*high.final_valid_pixel_fraction:.2f}','LOWPOP':f'{lowpass.population:,.0f}','HIGHPOP':f'{highfail.population:,.0f}','LOWSTD':f'{low.vstd_median:.3f}','HIGHSTD':f'{high.vstd_median:.3f}','LOWRES':f'{low.resid_rms_median:.3f}','HIGHRES':f'{high.resid_rms_median:.3f}','EVALUATED':str(s['evaluated_heldout_pairs']),'EXCLUDED':str(44-s['evaluated_heldout_pairs']),'RMSE':f"{s['holdout']['all_predictions']['pooled_rmse_mm']:.3f}",'PASSRMSE':f"{s['holdout']['training_mask_pass']['pooled_rmse_mm']:.3f}",'FAILRMSE':f"{s['holdout']['training_mask_fail']['pooled_rmse_mm']:.3f}",'LOWRMSE':f'{held.iloc[0].pooled_rmse_mm:.3f}','HIGHRMSE':f'{held.iloc[-1].pooled_rmse_mm:.3f}','REF':s['training_reference']}
    prediction=pd.read_csv(p/'heldout_prediction_comparison.csv').query("group == 'all_common'").set_index('model')
    v.update(COMMONRMSE=f"{prediction.loc['time_series','pooled_rmse_mm']:.3f}",LINEARRMSE=f"{prediction.loc['linear_velocity','pooled_rmse_mm']:.3f}",ZERORMSE=f"{prediction.loc['zero_displacement','pooled_rmse_mm']:.3f}")
    def fill(t):
        for k,value in v.items():t=t.replace('@@'+k+'@@',value)
        assert '@@' not in t
        return t
    maintext=r'''Full-stack quality rejection leaves @@FULLUSED@@ of 437 pairs for inversion; the training branch retains @@TRAINUSED@@ of 393 inputs. The full quality mask accepts @@VALIDPIX@@\% of pixels and @@VALIDPOP@@\% of the small area's allocated population. Among pixels with matched-input mean support below 0.2, @@LOWVALID@@\% still pass the fixed multi-index mask; the 0.8--1 group has @@HIGHVALID@@\% acceptance. Low coherence-screened support is therefore not equivalent to final processing rejection (Fig.~\ref{fig:matched}). Neither acceptance nor rejection is independent physical truth.

At a legacy-support threshold of 0.5, the low-support/accepted and high-support/rejected categories contain @@LOWPOP@@ and @@HIGHPOP@@ population allocation units, respectively. That legacy comparison also changes the acquisition period and sample. The matched-input bins provide the within-period comparison: median bootstrap velocity spread is @@LOWSTD@@ versus @@HIGHSTD@@ mm yr$^{-1}$ and median inversion residual is @@LOWRES@@ versus @@HIGHRES@@ mm for the lowest and highest support groups. These associations describe quality differences rather than a binary validity surrogate.

Of 44 excluded pair edges, @@EVALUATED@@ meet the recorded prediction/reference conditions. Pooled held-out LOS displacement RMSE is @@RMSE@@ mm across evaluable observations. Training-mask accepted and rejected locations give @@PASSRMSE@@ and @@FAILRMSE@@ mm, respectively; the lowest and highest training-support bins give @@LOWRMSE@@ and @@HIGHRMSE@@ mm. On common evaluable observations, time-series differences, training linear velocity and a zero-displacement baseline give @@COMMONRMSE@@, @@LINEARRMSE@@ and @@ZERORMSE@@ mm. This edge holdout reconstructs pairs between dates already represented in training; shared date-dependent atmospheric phase can also be reconstructed. These are residuals against excluded interferograms with shared acquisitions, not out-of-time forecasts or external velocity accuracies or evidence about permanently missing motion. Exclusions and per-pair results are retained in Supplementary S7.

\begin{figure}[t]\centering
\includegraphics[width=\linewidth]{figures/F7_matched_processing.pdf}
\caption{Matched LiCSBAS experiment in the fixed Bangkok rectangle. The legacy support map uses the 2016--2022 sample; its high/low split is 0.5 in panel b, compared with the 2019--2020 full-stack quality mask. Panel c separately includes the matched 437-pair input diagnostic. Both diagnostics use coherence cutoff $q=0.3$. Panel d groups held-out prediction residuals using training pairs only. Bin connections guide the eye; no independent-observation confidence interval is implied.}\label{fig:matched}
\end{figure}
'''
    (paper/'matched_results.tex').write_text(fill(maintext),encoding='utf-8')
    supplemental=r'''The upstream LiCSBAS2 commit is \path{2627e50a1c703becd4a0b18754b05c1cf8c564d5}. Both branches complete steps 11--16 without changes to tracked scientific source. A documented Windows I/O wrapper substitutes a native parameter reader for external grep and copies browse PNGs instead of creating symlinks. Its optional GDAL import only affects unused GeoTIFF helper functions. Input preparation uses Rasterio independently. All processing is serial with a fixed NumPy seed; package versions and the exact wrapper diff are retained.

The canonical processing raster has 301 columns and 401 rows, with actual affine transform recorded in \path{results/timeseries/geometry.json}; its pixel spacing is approximately 108 by 111 m at this latitude. The input frame is 062D\_07629\_131313. Global input connectivity is a selection requirement, not a guarantee of pixel-level connectivity. Of 437 full-stack inputs, @@FULLUSED@@ survive pair-level checks; of 393 training inputs, @@TRAINUSED@@ survive. Both original holdout membership and rejected-pair lists are saved. Held-out phase/coherence is never used by the training workflow.

Step 11 uses the upstream mean-coherence threshold 0.05 and unwrapped-coverage threshold 0.3. Step 12 uses a loop threshold of 1.5 rad. Step 13 uses least squares with regularization parameter 0.0001 and requires more than 104 valid interferograms for inversion. Step 14 retains the upstream 100 bootstrap draws and spatiotemporal-consistency calculation. Bootstrap velocity spread is a processing diagnostic, not a calibrated uncertainty interval for physical velocity.

Step 15 uses fixed C-band defaults with automatic threshold relaxation disabled: mean coherence at least 0.05, at least 156 valid interferograms, velocity spread at most 100 mm yr$^{-1}$, maximum connected duration at least one year, at most 10 temporal gaps, spatiotemporal inconsistency at most 5 mm, at most 50 interferograms without a loop, at most 5 loop errors and inversion residual RMS at most 2 mm. The combined mask therefore contains information beyond the $q=0.3$ input diagnostic. It also shares coherence information with that diagnostic. Rates in the saved mask logs use the upstream finite/non-reference denominator; reported domain fractions count all 120,701 processing cells and explicitly include the finite reference pixel.

Step 16 applies the upstream 2-km spatial and 21-day temporal filter, without detrending, DEM-error fitting or height-linear correction. Both filtered products are retained, but the held-out prediction is deliberately evaluated from \texttt{cum.h5}, the unfiltered training inversion. Thus prediction does not introduce a filtering-dependent smoothing comparison. No atmospheric correction or external GNSS datum is added. LOS displacement is relative and positive toward the satellite under the coefficient $-c/(4\pi f)$, with $f=5.405$ GHz; it is not converted to vertical motion.

For a held-out pair $(a,b)$, predicted displacement is the difference between training cumulative displacements at $b$ and $a$. Observed phase is converted to millimeters after subtracting its mean at the training reference area, \texttt{@@REF@@}. The reference is selected entirely from training data. Held-out pairs missing a required training date or finite/nonzero phase at that reference are excluded explicitly. There are @@EVALUATED@@ evaluated and @@EXCLUDED@@ excluded pairs. No spatial offset is fitted to minimize held-out errors. Prediction locations must have finite predicted displacement and valid nonzero held-out phase; low-coherence observed held-out values are not selectively discarded. Consequently these residuals include errors in the held-out observations as well as training predictions. Evaluability does not establish permanent-gap validity.

All-prediction pooled RMSE is @@RMSE@@ mm, versus @@PASSRMSE@@/@@FAILRMSE@@ mm inside/outside the training quality mask. Training-only support bins range from @@LOWRMSE@@ mm in the lowest group to @@HIGHRMSE@@ mm in the highest group. This comparison uses no held-out coherence in its strata. We additionally compare three predictions on identical evaluable observations: cumulative time-series differences, training HDF5 linear velocity multiplied by the pair interval in years (365.25 days), and zero relative displacement. Their pooled RMSE values are @@COMMONRMSE@@, @@LINEARRMSE@@ and @@ZERORMSE@@ mm. The velocity baseline uses the same final training reference as the cumulative series. Neither baseline uses held-out measurements for fitting. All held-out acquisition dates remain represented in training: this tests edge reconstruction, not prediction at unseen dates. Reconstructed date-dependent atmospheric phase can contribute to the difference from a linear or zero-displacement baseline, so the improvement does not establish deformation accuracy. Shared dates and atmospheric components limit independence, so spatial-pixel sample sizes and pair counts are descriptive denominators, not effective independent sample sizes. Five support thresholds (0.2, 0.3, 0.5, 0.7, 0.8), all four confusion categories, population/area weights, support-bin counts and quality medians are saved rather than selecting only one favorable threshold.

Evidence files are \path{support_finalmask_confusion.csv}, \path{support_quality_bins.csv}, \path{heldout_pairs.csv}, \path{heldout_support_bins.csv}, \path{heldout_prediction_comparison.csv}, \path{descriptive_correlations.csv} and \path{audit.json} within \path{results/timeseries/}. The audit verifies all twelve stage completions, absence of held-out edges from training input directories, population conservation in confusion tables, pooled residual reconstruction and independent recomputation of selected pair residuals. It verifies implementation and design, not external physical accuracy.

\begin{figure}[htbp]\centering
\includegraphics[width=\linewidth]{figures/S3_matched_quality.pdf}
\caption{Actual same-chain quality fields in the Bangkok processing rectangle. Panel a shows the unfiltered fitted LOS velocity only where the full quality mask passes. Other panels retain finite quality diagnostics and held-out RMSE. Symmetric velocity limits and the upper limits of other color scales use their 98th percentiles for readability; values outside those limits are clipped in color only and retained in the data. No map supplies independent GNSS accuracy or motion in unobserved locations.}\end{figure}
'''
    (paper/'matched_supplement.tex').write_text(fill(supplemental),encoding='utf-8')
    response=paper/'response_to_reviewers.md';text=response.read_text(encoding='utf-8')
    text=re.sub(r'\*\*Working scientific revision\.\*\*.*?Comment headings', '**Completed local scientific revision.** The experiment outputs have been audited and incorporated in the manuscript and Supplementary Information. Comment headings',text,count=1)
    start=text.index('Third, ',text.index('### Comment 1: The hidden-exposure'))
    end=text.index('\n\n**Changes and evidence:**',start)
    new=fill('Third, we completed a separate, connected 2019–2020 LiCSAR stack through LiCSBAS steps 11–16, both for all 437 inputs and for the 393-pair training subset after 44 date-selected edges were held out. The full quality mask accepts @@VALIDPIX@@% of pixels. Even in the matched-input support bin below 0.2, @@LOWVALID@@% pass the default multi-index quality mask. We therefore explicitly reject the inference that low sampled support itself proves final-product invalidity. At a legacy support threshold of 0.5, low-support/accepted and high-support/rejected classes contain @@LOWPOP@@ and @@HIGHPOP@@ population allocation units.\n\nThe @@EVALUATED@@ evaluable held-out pairs give pooled LOS displacement RMSE @@RMSE@@ mm; training-mask accepted/rejected locations give @@PASSRMSE@@/@@FAILRMSE@@ mm, and the lowest/highest training-support bins give @@LOWRMSE@@/@@HIGHRMSE@@ mm. On identical evaluable observations, cumulative time-series differences, training linear velocity and zero relative displacement yield @@COMMONRMSE@@, @@LINEARRMSE@@ and @@ZERORMSE@@ mm, respectively. Strata use training inputs only. These are internal edge-reconstruction residuals between dates already represented in training, potentially including shared atmospheric phase; they are not out-of-time forecasts, independent GNSS/leveling accuracy or validation of permanently missing locations. The result assesses one LiCSAR/LiCSBAS chain and does not invalidate the separate WabInSAR source. The full configuration, exclusions, confusion tables, quality distributions and residual records appear in Supplementary S7.')
    text=text[:start]+new+text[end:];text=text.replace('Fig. S1 and date-network table','Figs. S1–S2 and date-network table');response.write_text(text,encoding='utf-8')
    manuscript=paper/'manuscript.tex';t=manuscript.read_text(encoding='utf-8')
    abstract=fill(r'''Interferometric synthetic aperture radar (InSAR) support and population allocation jointly determine downstream summaries. We quantify their interaction through matched-input comparisons, controlled missingness, expanded sampling and alternative population models. In a fixed Chao Phraya footprint, 28 LiCSAR pairs give a mean population-weighted support deficit of \PopThirty{} million allocation units using native GHSL population and joint coherence--unwrapped validity at a coherence cutoff of 0.3. Redistributing the same population uniformly within 1-km cells increases this quantity by \UniformBiasMin{}--\UniformBiasMax{}\%, explained by within-cell population--support covariance. Controlled masking produces both error directions and small aggregate bias under random missingness. GHSL and WorldPop yield deficit shares of \GHSLJointPct{}\% and \WPJointPct{}\% on common coverage; equalizing totals preserves this difference. Expanding sampling to 224 pairs gives \SampleTwoTwentyFour{} million GHSL deficit units. In a separate 437-pair LiCSBAS experiment, @@LOWVALID@@\% of pixels with support below 0.2 still pass default processing quality criteria; excluded-pair predictions provide an internal residual check. A Fresno application repeats the allocation and masking comparisons using actual observation polygons. These results quantify support and allocation sensitivity, not verified subsidence exposure or unique people never observed. The protocol makes the target, denominator, allocation assumptions and validation limits explicit.''')
    t=re.sub(r'\\abstract\{.*?\}\n\\keywords',lambda _:r'\abstract{'+abstract+'}\n'+r'\keywords',t,flags=re.S)
    manuscript.write_text(t,encoding='utf-8');dump(paper/'matched_report_values.json',dict(values=v,source='results/timeseries CSV/JSON outputs and saved stage parameters'))
    print('MATCHED MANUSCRIPT/SI/RESPONSE SYNCHRONIZED',flush=True)

if __name__=='__main__':main()
